version: '3'

services:
  puppetserver:
    container_name: puppetserver
    hostname: puppet
    image:  puppet/puppetserver
    ports:
      - 8140
    volumes:
      - ./nodes/puppetserver/code:/etc/puppetlabs/code/
      - ./nodes/puppetserver/ssl:/etc/puppetlabs/puppet/ssl/
      - ./nodes/puppetserver/serverdata:/opt/puppetlabs/server/data/puppetserver/
  puppetdb-postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    # networks:
    #   - devops-nw
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    expose:
      - 5432
    volumes:
      - ./nodes/puppetdb-postgres/data:/var/lib/postgresql/data/
  puppetdb:
    depends_on:
      - puppetdb-postgres
    hostname: puppetdb
    container_name: puppetdb
    image: puppet/puppetdb
    ports:
      - 8080
      - 8081
    volumes:
      - ./nodes/puppetdb/ssl:/etc/puppetlabs/puppet/ssl/
  ubuntu1:
    hostname: ubuntu1
    container_name: ubuntu1
    image:  puppet/puppet-agent-ubuntu
    volumes:
      - ./nodes/ubuntu1/ssl:/etc/puppetlabs/puppet/ssl/
    

# networks:
#   devops-nw: